### ISSUE TITLE
Any plans for paper pre-release?

### ISSUE THREAD

**Issue by U-AMC** [ouguangjun/Leg-KILO#1]
Hello!! And thanks for sharing your research including the Leg-KILO dataset. 
I've been inspired and interested in your research recently.
Are there any plans for uploading papers on repo or arxiv before the paper acceptance? 
Thanks!

**Comment by ouguangjun** [comment]
@U-MAC Thank you very much for your attention to our work. 
At present, the paper is still under review. We plan to put it on arvix for some time in the future

**Comment by U-MAC** [comment]
@ouguangjun Thanks for informing. Can't wait to see the paper

**Comment by kao-yang** [comment]
I see that your nice paper was accepted by RA-L 2024. Would U like to share your paper now?

**Comment by U-AMC** [comment]
@kao-yang  I got an update from the IEEE Xplore
[Leg-KILO](https://ieeexplore.ieee.org/document/10631676)
Here's the link to the paper
