### ISSUE TITLE
关于系统运行效率

### ISSUE THREAD

**Issue by moonsheep99** [ouguangjun/Leg-KILO#4]
首先，感谢您这么棒的开源工作！

通过文章发现工作是基于因子图优化的，实验可以以50ms处理速度运行，真的很快。
文中说此计算效率得益于ikd-tree地图的增量更新，这让我有些想不通，因为因子图优化往往时间消耗很大。与同样基于ikd-tree的几个直接配准+滤波的方法（FAST-LIO2系列），和点云特征+因子图优化的方法相比，可以这么理解吗：大部分运行效率的差异实则源自地图管理，小部分差异源于后端方法和点云处理方法？

另外，想咨询一下您测试过腿部里程计，LiDAR里程计（应该是10Hz？）和整体系统（因子图优化后）的输出频率嘛？

后续我也会着手测试一下，再次感谢您的开源工作！

**Comment by ouguangjun** [comment]
感谢你的关注。你说的没错，地图维护以及特征匹配占据大多数算力。gtsam的因子图优化其实是很快的，相对于地图来说可以忽略不计。 腿足里程计频率是跟编码器IMU一样，因子图优化后的输出频率是跟激光雷达一样。

**Comment by moonsheep99** [comment]
好的，感谢您的答复！
